// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bukrkbopsgkbylrpeydo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1a3JrYm9wc2drYnlscnBleWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzM5NjgsImV4cCI6MjA2NzE0OTk2OH0.fmlmTaSfd7yNoFW91q03khMPGxFVfHwABWwRBlKX_oc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});